# -*- coding: utf-8 -*-
"""Recommendation_System_assignments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d_i2SY_ENbsZYd3Mbqy5ID9ITZm_kPvw
"""

import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import correlation,cosine

data=pd.read_csv('C://datasets//book.csv',encoding='ISO-8859-1')

data

data=data.drop('Unnamed: 0',axis=1)

data

data.isnull().sum()

data.info()

data.shape

data=data.rename(columns={'User.ID':'userid','Book.Title':'books','Book.Rating':'rating'})

data

len(data.userid.unique())

len(data.books.unique())

books=data.pivot_table(index='userid',columns='books',values='rating').reset_index(drop=True)

books

books.index=data.userid.unique()

books

books.fillna(0,inplace=True)

books

user_sim=1-pairwise_distances(books.values,metric='cosine')
user_sim

np.fill_diagonal(user_sim,0)

user_sim

user_df=pd.DataFrame(user_sim)
user_df

user_df.index=data.userid.unique()

user_df.columns=data.userid.unique()

user_df[0:40]

user_df.idxmax(axis=1)

data[(data['userid']==276729)|(data['userid']==276726)]

user1=data[(data['userid']==276729)]
user2=data[data['userid']==276726]

user1

user2

data

pd.merge(user1,user2,on='books',how='outer')

